server:
  port: 8080
  servlet:
    context-path: /SpringBoot-SpringSecurity
spring:
  application:
    name: SpringBoot-SpringSecurity
  mvc:
    view:
      prefix: =/WEB-INF/views/
      suffix: .jsp